version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: world_cup
      MYSQL_ROOT_PASSWORD: 'russia'
    networks:
      - backend
    ports:
      - "5001:3306"
    restart: always
    volumes:
      - ~/data/mysql_data:/var/lib/mysql
  app:
    command: >
      bash -c
        "
        ./wait-for-mysql.sh db 3306 russia world_cup
        python manage.py makemigrations
        python manage.py migrate
        python populate_database.py
        python update_paul_user.py
        python manage.py runserver 0.0.0.0:8000"
    build: ./world-cup-predictions-back
    environment:
      - DJANGO_SETTINGS_MODULE=world_cup_predictions.settings
      - PYTHONDONTWRITEBYTECODE=1
    restart: on-failure
    ports:
      - "8002:8000"
    networks:
      - backend
    depends_on:
      - db
  frontend:
    build: ./world-cup-predictions-front
    command: "http-server ./dist"
    restart: always
    depends_on:
      - app
    networks:
      - backend
    ports:
      - "8080:8080"
    env_file:
      ./world-cup-predictions-front/.env
networks:
  backend:
    driver: bridge